# Microservicio Compras
spring:
  application:
    name: Compras
  datasource:
    url: jdbc:postgresql://localhost:5432/Compras
    username: postgres
    password: virginia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  ProductoAPI:
    url: http://localhost:8081/Producto
  VentaAPI:
    url: http://localhost:8083/Ventas
