# Microservicio Ventas
spring:
  application:
    name: Ventas
  datasource:
    url: jdbc:postgresql://localhost:5432/Ventas
    username: postgres
    password: virginia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  CompraAPI:
    url: http://localhost:8082/Compra